"""empty message

Revision ID: 6088f8fc5a86
Revises: 5faab0cd4d6c
Create Date: 2024-09-20 09:58:27.063924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6088f8fc5a86'
down_revision = '5faab0cd4d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('away', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('home_goals', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('away_goals', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['home'], ['name'])
        batch_op.create_foreign_key(None, 'team', ['away'], ['name'])
        batch_op.drop_column('team_b')
        batch_op.drop_column('goals_b')
        batch_op.drop_column('team_a')
        batch_op.drop_column('goals_a')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals_a', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('team_a', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('goals_b', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('team_b', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['team_b'], ['name'])
        batch_op.create_foreign_key(None, 'team', ['team_a'], ['name'])
        batch_op.drop_column('away_goals')
        batch_op.drop_column('home_goals')
        batch_op.drop_column('away')
        batch_op.drop_column('home')

    # ### end Alembic commands ###
