"""empty message

Revision ID: f7eda0ec28be
Revises: 6088f8fc5a86
Create Date: 2024-09-20 10:41:17.395301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7eda0ec28be'
down_revision = '6088f8fc5a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_team')
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_a', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('team_b', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('goals_a', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('goals_b', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_match_home_team', type_='foreignkey')
        batch_op.drop_constraint('fk_match_away_team', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_match_team_b_team'), 'team', ['team_b'], ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_match_team_a_team'), 'team', ['team_a'], ['name'])
        batch_op.drop_column('away_goals')
        batch_op.drop_column('home_goals')
        batch_op.drop_column('away')
        batch_op.drop_column('home')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('away', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('home_goals', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('away_goals', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_match_team_a_team'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_match_team_b_team'), type_='foreignkey')
        batch_op.create_foreign_key('fk_match_away_team', 'team', ['away'], ['name'])
        batch_op.create_foreign_key('fk_match_home_team', 'team', ['home'], ['name'])
        batch_op.drop_column('goals_b')
        batch_op.drop_column('goals_a')
        batch_op.drop_column('team_b')
        batch_op.drop_column('team_a')

    op.create_table('_alembic_tmp_team',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
